/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerlofRouteImport } from './routes/verlof'
import { Route as UrenRouteImport } from './routes/uren'
import { Route as MedewerkersRouteImport } from './routes/medewerkers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KlantenRouteImport } from './routes/klanten'
import { Route as InstellingenRouteImport } from './routes/instellingen'
import { Route as BedrijfsgegevensRouteImport } from './routes/bedrijfsgegevens'
import { Route as ArtikelenRouteImport } from './routes/artikelen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectenIndexRouteImport } from './routes/projecten.index'
import { Route as OffertesIndexRouteImport } from './routes/offertes.index'
import { Route as ProjectenIdRouteImport } from './routes/projecten.$id'
import { Route as OffertesIdRouteImport } from './routes/offertes.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const VerlofRoute = VerlofRouteImport.update({
  id: '/verlof',
  path: '/verlof',
  getParentRoute: () => rootRouteImport,
} as any)
const UrenRoute = UrenRouteImport.update({
  id: '/uren',
  path: '/uren',
  getParentRoute: () => rootRouteImport,
} as any)
const MedewerkersRoute = MedewerkersRouteImport.update({
  id: '/medewerkers',
  path: '/medewerkers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KlantenRoute = KlantenRouteImport.update({
  id: '/klanten',
  path: '/klanten',
  getParentRoute: () => rootRouteImport,
} as any)
const InstellingenRoute = InstellingenRouteImport.update({
  id: '/instellingen',
  path: '/instellingen',
  getParentRoute: () => rootRouteImport,
} as any)
const BedrijfsgegevensRoute = BedrijfsgegevensRouteImport.update({
  id: '/bedrijfsgegevens',
  path: '/bedrijfsgegevens',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelenRoute = ArtikelenRouteImport.update({
  id: '/artikelen',
  path: '/artikelen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectenIndexRoute = ProjectenIndexRouteImport.update({
  id: '/projecten/',
  path: '/projecten/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffertesIndexRoute = OffertesIndexRouteImport.update({
  id: '/offertes/',
  path: '/offertes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectenIdRoute = ProjectenIdRouteImport.update({
  id: '/projecten/$id',
  path: '/projecten/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OffertesIdRoute = OffertesIdRouteImport.update({
  id: '/offertes/$id',
  path: '/offertes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artikelen': typeof ArtikelenRoute
  '/bedrijfsgegevens': typeof BedrijfsgegevensRoute
  '/instellingen': typeof InstellingenRoute
  '/klanten': typeof KlantenRoute
  '/login': typeof LoginRoute
  '/medewerkers': typeof MedewerkersRoute
  '/uren': typeof UrenRoute
  '/verlof': typeof VerlofRoute
  '/offertes/$id': typeof OffertesIdRoute
  '/projecten/$id': typeof ProjectenIdRoute
  '/offertes/': typeof OffertesIndexRoute
  '/projecten/': typeof ProjectenIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artikelen': typeof ArtikelenRoute
  '/bedrijfsgegevens': typeof BedrijfsgegevensRoute
  '/instellingen': typeof InstellingenRoute
  '/klanten': typeof KlantenRoute
  '/login': typeof LoginRoute
  '/medewerkers': typeof MedewerkersRoute
  '/uren': typeof UrenRoute
  '/verlof': typeof VerlofRoute
  '/offertes/$id': typeof OffertesIdRoute
  '/projecten/$id': typeof ProjectenIdRoute
  '/offertes': typeof OffertesIndexRoute
  '/projecten': typeof ProjectenIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artikelen': typeof ArtikelenRoute
  '/bedrijfsgegevens': typeof BedrijfsgegevensRoute
  '/instellingen': typeof InstellingenRoute
  '/klanten': typeof KlantenRoute
  '/login': typeof LoginRoute
  '/medewerkers': typeof MedewerkersRoute
  '/uren': typeof UrenRoute
  '/verlof': typeof VerlofRoute
  '/offertes/$id': typeof OffertesIdRoute
  '/projecten/$id': typeof ProjectenIdRoute
  '/offertes/': typeof OffertesIndexRoute
  '/projecten/': typeof ProjectenIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artikelen'
    | '/bedrijfsgegevens'
    | '/instellingen'
    | '/klanten'
    | '/login'
    | '/medewerkers'
    | '/uren'
    | '/verlof'
    | '/offertes/$id'
    | '/projecten/$id'
    | '/offertes/'
    | '/projecten/'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artikelen'
    | '/bedrijfsgegevens'
    | '/instellingen'
    | '/klanten'
    | '/login'
    | '/medewerkers'
    | '/uren'
    | '/verlof'
    | '/offertes/$id'
    | '/projecten/$id'
    | '/offertes'
    | '/projecten'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/artikelen'
    | '/bedrijfsgegevens'
    | '/instellingen'
    | '/klanten'
    | '/login'
    | '/medewerkers'
    | '/uren'
    | '/verlof'
    | '/offertes/$id'
    | '/projecten/$id'
    | '/offertes/'
    | '/projecten/'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtikelenRoute: typeof ArtikelenRoute
  BedrijfsgegevensRoute: typeof BedrijfsgegevensRoute
  InstellingenRoute: typeof InstellingenRoute
  KlantenRoute: typeof KlantenRoute
  LoginRoute: typeof LoginRoute
  MedewerkersRoute: typeof MedewerkersRoute
  UrenRoute: typeof UrenRoute
  VerlofRoute: typeof VerlofRoute
  OffertesIdRoute: typeof OffertesIdRoute
  ProjectenIdRoute: typeof ProjectenIdRoute
  OffertesIndexRoute: typeof OffertesIndexRoute
  ProjectenIndexRoute: typeof ProjectenIndexRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verlof': {
      id: '/verlof'
      path: '/verlof'
      fullPath: '/verlof'
      preLoaderRoute: typeof VerlofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uren': {
      id: '/uren'
      path: '/uren'
      fullPath: '/uren'
      preLoaderRoute: typeof UrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medewerkers': {
      id: '/medewerkers'
      path: '/medewerkers'
      fullPath: '/medewerkers'
      preLoaderRoute: typeof MedewerkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klanten': {
      id: '/klanten'
      path: '/klanten'
      fullPath: '/klanten'
      preLoaderRoute: typeof KlantenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instellingen': {
      id: '/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof InstellingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedrijfsgegevens': {
      id: '/bedrijfsgegevens'
      path: '/bedrijfsgegevens'
      fullPath: '/bedrijfsgegevens'
      preLoaderRoute: typeof BedrijfsgegevensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikelen': {
      id: '/artikelen'
      path: '/artikelen'
      fullPath: '/artikelen'
      preLoaderRoute: typeof ArtikelenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projecten/': {
      id: '/projecten/'
      path: '/projecten'
      fullPath: '/projecten/'
      preLoaderRoute: typeof ProjectenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offertes/': {
      id: '/offertes/'
      path: '/offertes'
      fullPath: '/offertes/'
      preLoaderRoute: typeof OffertesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projecten/$id': {
      id: '/projecten/$id'
      path: '/projecten/$id'
      fullPath: '/projecten/$id'
      preLoaderRoute: typeof ProjectenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offertes/$id': {
      id: '/offertes/$id'
      path: '/offertes/$id'
      fullPath: '/offertes/$id'
      preLoaderRoute: typeof OffertesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtikelenRoute: ArtikelenRoute,
  BedrijfsgegevensRoute: BedrijfsgegevensRoute,
  InstellingenRoute: InstellingenRoute,
  KlantenRoute: KlantenRoute,
  LoginRoute: LoginRoute,
  MedewerkersRoute: MedewerkersRoute,
  UrenRoute: UrenRoute,
  VerlofRoute: VerlofRoute,
  OffertesIdRoute: OffertesIdRoute,
  ProjectenIdRoute: ProjectenIdRoute,
  OffertesIndexRoute: OffertesIndexRoute,
  ProjectenIndexRoute: ProjectenIndexRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
