ALTER TABLE public.employees
  ADD COLUMN contract_type TEXT,
  ADD COLUMN start_date DATE,
  ADD COLUMN probation_end_date DATE,
  ADD COLUMN end_date DATE,
  ADD COLUMN hours_per_week NUMERIC,
  ADD COLUMN work_days TEXT,
  ADD COLUMN hourly_rate NUMERIC,
  ADD COLUMN monthly_salary NUMERIC,
  ADD COLUMN vacation_days_per_year NUMERIC DEFAULT 20,
  ADD COLUMN iban TEXT,
  ADD COLUMN bic TEXT,
  ADD COLUMN payroll_tax_credit BOOLEAN DEFAULT false,
  ADD COLUMN special_arrangement TEXT,
  ADD COLUMN liability_policy_number TEXT,
  ADD COLUMN accident_policy_number TEXT,
  ADD COLUMN insurance_notes TEXT,
  ADD COLUMN arbo_check_date DATE,
  ADD COLUMN medical_exam_date DATE,
  ADD COLUMN safety_instructions_signed BOOLEAN DEFAULT false,
  ADD COLUMN arbo_notes TEXT;